server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/laravel-crm/vendor/orchestra/testbench-core/laravel/public;
    index index.php index.html;

    server_name crm.techfusion-alchemy.xyz 35.255.93.72;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param TESTBENCH_CONFIG_FILE /var/www/laravel-crm/testbench.yaml;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
